module.exports = {
    rules: {
        'eol-last': ['error', 'always'],
        'space-before-blocks': 'error',
        'keyword-spacing': ['error', {before: true, after: true}],
        'object-curly-spacing': ['error', 'never'],
        'comma-spacing': ['error', {before: false, after: true}],
        'semi-spacing': 'error',
        'computed-property-spacing': 'error',
        'space-in-parens': ['error', 'never'],
        'no-extra-semi': 'error',
        'semi-style': ['error', 'last'],
        'semi': ['error'],
        'arrow-body-style': ['error', 'as-needed'],
        '@typescript-eslint/indent': ['error', 4, { SwitchCase: 1 }],
        'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0, maxBOF: 0 }],
        'no-console': ['error', { allow: ['error'] }],
        'no-tabs': 'error',
        'quotes': ['error', 'single'],
        'quote-props': [2, 'consistent-as-needed', { keywords: false }],
        'key-spacing': [
            2,
            { mode: 'strict', beforeColon: false, afterColon: true },
        ],
        'id-length': ['error', { min: 2, properties: 'never' }],
        'max-len': ['error', { code: 130 }],
        'max-params': ['error', 5],
        'max-nested-callbacks': ['error', 5],
        'max-depth': ['error', 5],
        'no-use-before-define': 'off',
        'space-infix-ops': 'error',
        'arrow-spacing': 'error',

        'no-param-reassign': [
            'error',
            {
                props: true,
                ignorePropertyModificationsFor: [
                    // for .reduce only
                    'acc',
                    'arr',
                    'obj',
                    'result',
                ],
            },
        ],
        'padding-line-between-statements': [
            'error',
            { blankLine: 'always', prev: '*', next: 'return' },
        ],
        'no-debugger': 'error',
        'prefer-const': 'error',
        'array-callback-return': ['error', {allowImplicit: true}],
        'class-methods-use-this': ['error', {exceptMethods: ['componentDidCatch']}],
        'lines-between-class-members': ['error', 'always', {exceptAfterSingleLine: true}],
        'consistent-return': 'warn',
        'default-case': 'warn',
        'dot-notation': ['error', {allowKeywords: true}],
        'eqeqeq': ['error', 'always', {null: 'ignore'}],
        'guard-for-in': 'error',
        'max-classes-per-file': ['error', 1],
        'no-alert': 'warn',
        'no-caller': 'error',
        'no-case-declarations': 'error',
        'no-empty-function': 'error',
        'no-empty-pattern': 'error',
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'error',
        'no-extra-label': 'error',
        'no-fallthrough': 'error',
        'no-floating-decimal': 'error',
        'no-global-assign': ['error', {exceptions: []}],
        'no-implied-eval': 'error',
        'no-labels': 'error',
        'no-lone-blocks': 'error',
        'no-loop-func': 'error',
        'no-multi-spaces': [
            'error',
            {
                ignoreEOLComments: false,
            },
        ],
        'no-new': 'error',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-octal': 'error',
        'no-octal-escape': 'error',
        'no-proto': 'error',
        'no-restricted-properties': 'error',
        'no-return-assign': ['error', 'always'],
        'no-return-await': 'error',
        'no-script-url': 'error',
        'no-self-assign': 'error',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-throw-literal': 'error',
        'no-unused-expressions': 'error',
        'no-useless-catch': 'error',
        'no-useless-concat': 'error',
        'no-useless-escape': 'error',
        'no-useless-return': 'error',
        'no-void': 'error',
        'no-with': 'error',
        'no-underscore-dangle': 'error',
        'prefer-promise-reject-errors': ['error', {allowEmptyReject: true}],
        'radix': 'error',
        'vars-on-top': 'error',
        'yoda': 'error',
    },
};
