module.exports = {
    plugins: ['react'],
    rules: {
        'react/jsx-filename-extension': [1, { extensions: ['.tsx'] }],
        'react/jsx-wrap-multilines': [2, {
			"declaration": "parens-new-line",
			"assignment": "parens-new-line",
			"return": "parens-new-line",
			"arrow": "parens-new-line",
			"condition": "parens-new-line",
			"logical": "parens-new-line",
			"prop": "parens-new-line"
		}],
        'react/jsx-tag-spacing': 'error',
        'jsx-quotes': ['error', 'prefer-double'],
        'react/jsx-key': 'error',
        'react/jsx-no-comment-textnodes': 'error',
        'react/jsx-no-duplicate-props': 'error',
        'react/jsx-uses-react': 'error',
        'react/jsx-uses-vars': 'error',
        'react/no-children-prop': 'error',
        'react/no-danger': 'error',
        'react/jsx-curly-brace-presence': 'error',
        'react/jsx-closing-bracket-location': ['error', 'tag-aligned'],
        'react/no-danger-with-children': 'error',
        'react/no-deprecated': 'error',
        'react/no-direct-mutation-state': 'error',
        'react/no-find-dom-node': 'error',
        'react/no-is-mounted': 'error',
        'react/no-render-return-value': 'error',
        'react/no-string-refs': 'error',
        'react/no-unescaped-entities': 'error',
        'react/no-unknown-property': 'error',
        'react/no-unsafe': 0,
        'react/react-in-jsx-scope': 'error',
        'react/require-render-return': 'error',
    },
};
